USE [master]
GO

/****** Object:  Database [GestionEnchereDB]    Script Date: 2018-11-20 19:21:03 ******/
CREATE DATABASE [GestionEnchereDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GestionEnchere', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\GestionEnchere.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GestionEnchere_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\GestionEnchere_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GestionEnchereDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GestionEnchereDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GestionEnchereDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GestionEnchereDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GestionEnchereDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GestionEnchereDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GestionEnchereDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET RECOVERY FULL 
GO

ALTER DATABASE [GestionEnchereDB] SET  MULTI_USER 
GO

ALTER DATABASE [GestionEnchereDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GestionEnchereDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GestionEnchereDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GestionEnchereDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GestionEnchereDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GestionEnchereDB] SET QUERY_STORE = OFF
GO

USE [GestionEnchereDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GestionEnchereDB] SET  READ_WRITE 
GO


